# Generated by Django 4.2 on 2023-04-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
